[build.environment]
DART_SASS_VERSION = "1.93.2"
GO_VERSION = "1.25.3"
HUGO_VERSION = "0.155.3"
NODE_VERSION = "24.13.0"

[build]
publish = "public"
command = """\
  git config core.quotepath false && \
  hugo --gc --minify --baseURL "${URL}"
  """
